sudo: required

language: python

services:
  - docker
  - elasticsearch
  - mongodb

addons:
  postgresql: '9.6'
    apt:
      packages:
        - postgresql-9.6-postgis-2.3

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -U postgres -c "create extension postgis"
  - docker-compose -f docker-compose.travis.yml up --build -d 
  - sleep 15  # wait for PostgreSQl and Elasticsearch to start

script:
  # use --keepdb to avoid OperationalError during teardown in case any
  # db connections are still open from threads in TransactionTestCases
  # - docker exec cyphon_cyphon_1 python manage.py test --noinput --keepdb
  # - docker exec cyphon_cyphon_1 coverage run manage.py test --noinput --keepdb
  - cd django
  - coverage run manage.py test --noinput --keepdb

after_success:
  # - pwd
  # - ls -a
  # - cd django
  # - pwd
  # - ls -a
  # - cat .coverage
  # - mv .coverage .coverage.123
  # - coverage combine --append
  - coverage
  - coveralls

after_script:
  - docker-compose down
