# Creates a minimal stack for testing Cyphon Engine on Travis CI.

version: '2'

services:

  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"

  geoip:
    image: dunbar/geoip:latest
    volumes:
      - /home/travis/build/dunbarcyber/cyphon/GeoIP:/usr/share/cyphondock

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
